### ISSUE TITLE
Raspberry Pi Foundation Projects

### ISSUE THREAD

**Issue by dosaki** [TheKeyholdingCompany/level-up-dev#1]
@deanhet  Do you think it's worth adding the RaspberryPi Foundation projects?
I use these with the kids that I teach and often the parents do them too.
Some might be a little childish but I found that they're really good at getting people started from 0 knowledge because it seems less daunting

Web:

- https://projects.raspberrypi.org/en/codeclub/webdev-module-1
- ﻿﻿https://projects.raspberrypi.org/en/codeclub/webdev-module-2﻿

﻿Python:

- ﻿﻿https://projects.raspberrypi.org/en/pathways/python-intro﻿
- ﻿﻿https://projects.raspberrypi.org/en/pathways/more-python﻿
- ﻿﻿https://projects.raspberrypi.org/en/codeclub/python-module-1﻿
- ﻿﻿https://projects.raspberrypi.org/en/codeclub/python-module-2

**Comment by deanhet** [comment]
Absolutely, when I was teaching I done a lot of hour of code (https://code.org/hourofcode/overview) with the kids. 
They were bordering on too old for some of it but the core mechanics are solid and once you get over that it's themed for kids, is still really fun.

Feel free to add the above where you think is appropriate. I don't mind leaving a whole pile of TODO's everywhere just now.
